"""
review_images.py — AI-powered image QA for The Interested Indian pipeline.

Reads image_prompts_one_line_per_prompt.md, loads each generated image from
{project}/images/, sends it to Claude with a style/content rubric, and writes
a review report to {project}/review_report.md.

Usage:
    python review_images.py --project ep01
    python review_images.py --project ep01 --shot 07        # single shot
    python review_images.py --project ep01 --fail-only      # issues only
    python review_images.py --project ep01 --model sonnet   # sonnet for the whole batch
    python review_images.py --project ep01 --no-recheck     # haiku only, skip sonnet recheck

Requirements:
    pip install anthropic
    ANTHROPIC_API_KEY set in environment (or .env file in this folder)

Cost estimate (Haiku): ~$0.01–0.02 per image → ~$1–2 for all 90 images
Cost estimate (Sonnet): ~$0.05–0.10 per image → ~$4–9 for all 90 images

Two-tier review (default): the bulk pass runs on --model (haiku by default), then any
shot that comes back WARN or FAIL is automatically re-reviewed with Sonnet — Haiku is
cheap but occasionally hallucinates a style/content verdict (confirmed on real shots),
so the pricier model only gets used on the small slice that actually needs a second
opinion instead of the whole batch. Pass --no-recheck to disable, or --model sonnet to
run Sonnet on everything from the start (recheck is skipped in that case, it'd be redundant).
"""

import argparse
import base64
import json
import os
import re
import sys
import time
from datetime import datetime
from pathlib import Path

try:
    import anthropic
except ImportError:
    print("❌ anthropic package not found. Run: pip install anthropic")
    sys.exit(1)

# Reuse route_images.py's TYPE classification (incl. MAP_ARGS/CHART_ARGS validation and
# downgrade-to-CARTOON fallback logic) so the review judges each shot against the style
# it was ACTUALLY routed/generated as, not just a raw TYPE field guess.
sys.path.insert(0, str(Path(__file__).parent))
import route_images

# ── constants ──────────────────────────────────────────────────────────────────
PROMPTS_FILE = "image_prompts_one_line_per_prompt.md"

MODELS = {
    "haiku":  "claude-haiku-4-5-20251001",   # fast, cheap — default
    "sonnet": "claude-sonnet-5",              # deeper review
}
DEFAULT_MODEL = "haiku"

DELAY_BETWEEN_CALLS = 0.5   # seconds — avoids rate-limit bursts

# Per-TYPE style guides. Only CARTOON shots are AI-generated illustrations held to the
# flat-cartoon rubric — MAP/CHART/PHOTO shots are generated by dedicated non-AI tools
# (GeoJSON renderer, matplotlib, Pexels) and must be judged against THEIR own correct style,
# not cartoon-style compliance. Previously every shot was judged with the cartoon guide,
# which hard-FAILed correct MAP/CHART/PHOTO output for "not being a flat cartoon."
STYLE_GUIDES = {
    "CARTOON": """
CHANNEL STYLE GUIDE — this is a CARTOON shot (AI-illustrated, The Interested Indian house style):
- Flat digital cartoon illustration — expressive characters with bold black outlines
- Mascot: chubby round cartoon character with big round glasses, thick eyebrows, short stubby arms.
  Should look friendly and slightly exasperated. NOT a stick figure — detailed cartoon face is correct.
- Background: warm cream (#FAF7F2), pale sky blue (#E8F4F8), or soft yellow (#FFF8E7). Light, not white.
  Never dark. Subtle warmth.
- Color palette: Crimson, Navy Blue, Forest Green, Warm Orange, Gold, Teal, Dusty Red, Amber.
  Used actively and vibrantly — colorful, not muted.
- No photorealism, no 3D renders. Flat cartoon is correct. Gradients are acceptable if subtle.
- Aspect ratio: 16:9 landscape
- Text in images: should be MINIMAL — all overlay text is added in post-production by PIL.
  Do NOT fail an image for missing overlay text. The overlay stage handles that separately.
""",
    "MAP": """
CHANNEL STYLE GUIDE — this is a MAP shot (accurate GeoJSON-rendered map, NOT AI-illustrated):
- This is a real geographic map of India rendered from boundary data, not a cartoon illustration.
  There is NO mascot and NO cartoon character in this shot type — that is correct, not a defect.
- Correct look: accurate state/UT borders, color-coded regions with distinct colors, bold black
  borders, the specific state(s)/region named in INTENDED VISUAL clearly highlighted, clean labels.
- Photorealism/3D is irrelevant here — this is a flat vector map either way. Judge geographic
  accuracy and whether the right region is highlighted, NOT whether it "looks like a cartoon."
- Aspect ratio: 16:9 landscape
- Text in images: overlay text is added separately by PIL. Do NOT fail for missing overlay text.
""",
    "CHART": """
CHANNEL STYLE GUIDE — this is a CHART shot (matplotlib data visualization, NOT AI-illustrated):
- This is a rendered chart (bar/pie/timeline/stat card), not a cartoon illustration.
  There is NO mascot and NO cartoon character in this shot type — that is correct, not a defect.
- Correct look: clean, readable chart with legible labels/values/axes that match the data described
  in INTENDED VISUAL, clear visual hierarchy, no overlapping or cut-off text.
- Judge whether the chart accurately represents the described data and is legible, NOT whether it
  "looks like a cartoon."
- Aspect ratio: 16:9 landscape
- Text in images: chart labels/values/numbers ARE part of this generated image (unlike cartoon/map
  shots) — check them carefully for typos as usual. Do not expect further PIL overlay text on top.
""",
    "PHOTO": """
CHANNEL STYLE GUIDE — this is a PHOTO shot (real stock photograph from Pexels, NOT AI-illustrated):
- This is a real-world photograph, not a cartoon illustration. Photorealism is CORRECT and REQUIRED
  for this shot type — do not flag it as violating the cartoon style.
  There is NO mascot and NO cartoon character in this shot type — that is correct, not a defect.
- Judge instead: does the photo plausibly depict the real-world subject/scene described in
  INTENDED VISUAL and NARRATION? Is it reasonably in focus, well-composed, and free of an obvious
  stock-site watermark?
- Aspect ratio: 16:9 landscape preferred, but stock photography may vary — mark ratio_ok true unless
  the crop is badly distorted or unusable.
- Text in images: overlay text is added separately by PIL. Do NOT fail for missing overlay text.
""",
}

REVIEW_PROMPT = """\
You are a quality reviewer for an animated video essay titled "{title}" for The Interested
Indian — a YouTube channel covering Indian history, geography, geopolitics, and administrative
dynamics. Review the attached image against the specifications below and respond ONLY with valid JSON.

SHOT: {shot}
SHOT TYPE: {shot_type}
FILENAME: {filename}
NARRATION: "{narration}"
INTENDED VISUAL: {prompt}
{gen_args_block}OVERLAY TEXT REQUIRED: {overlay}
ANIMATION CUE: {cue}

{style_guide}

THIS VIDEO'S TOPIC: {title}
Judge on-topic-ness and factual correctness using THIS SHOT's own NARRATION and INTENDED VISUAL
above — they are specific to this episode and are your source of truth, not a fixed list. Any
specific number, date, or proper noun mentioned in NARRATION or INTENDED VISUAL must be
spelled/rendered correctly if it appears as visible text in the image; flag it under no_typos if wrong.
Any image showing content from a completely unrelated topic (recipes, sports, foreign countries,
unrelated people, product advertisements, cooking etc. — i.e. clearly unrelated to "{title}" or
this shot's own NARRATION/INTENDED VISUAL) is off-topic.

RUBRIC — check each dimension:
1. style_ok       : Does it match the STYLE GUIDE above FOR THIS SHOT'S TYPE ({shot_type})?
                    A MAP/CHART/PHOTO shot correctly has no mascot/cartoon-style — judge it
                    against its own type's guide, not the cartoon rubric.
2. content_match  : For CARTOON/PHOTO shots, does the image clearly depict what INTENDED
                    VISUAL describes? For MAP/CHART shots, IGNORE INTENDED VISUAL for this
                    check — it's a narrative concept sketch (often mentioning the channel
                    mascot or illustrative framing) that generate_chart.py/generate_india_map.py
                    NEVER actually renders; a MAP/CHART shot correctly has none of that. Instead
                    judge content_match against GENERATION ARGS above: does the chart/map
                    actually represent that data/region?
3. overlay_ok     : ALWAYS mark true. Overlay text is added by a separate PIL stage AFTER
                    image generation — it will NOT be in the AI-generated image. Never fail
                    an image for missing overlay text.
4. ratio_ok       : Is the image landscape / 16:9? (mark true if unsure)
5. no_artifacts   : Is the image free of AI generation errors (mangled text, extra limbs,
                    distorted shapes, blurry regions)?
6. no_typos       : Read ALL visible text in the image carefully. Is it free of spelling mistakes,
                    wrong numbers, garbled words, or incorrect proper nouns? Compare against any
                    specific number/date/proper noun in THIS SHOT's own NARRATION or INTENDED
                    VISUAL above. Mark false if ANY text is wrong.
7. on_topic       : Does the image relate to THIS VIDEO'S TOPIC and this shot's own NARRATION/
                    INTENDED VISUAL? Mark false if the image appears to belong to a completely
                    different video or subject matter.
8. no_watermark   : Is the image free of watermarks, AI generator logos, stock photo badges,
                    or platform UI elements (e.g. Midjourney grid lines, DALL-E watermarks)?

TYPO REPORTING: If no_typos is false, list the exact wrong text found and what it should be.

VERDICT rules:
- "PASS"  : All dimensions OK (style correct FOR THIS SHOT'S TYPE, correct content, no bad artifacts)
- "WARN"  : 1–2 minor issues — for CARTOON: mascot proportions slightly off, minor composition
            issue; for MAP: wrong shade or minor label issue; for CHART: slightly cramped labels;
            for PHOTO: composition a bit off; in general, content mostly right but one element missing
- "FAIL"  : Any of: WRONG STYLE FOR THIS SHOT'S TYPE — i.e. a CARTOON shot that is a photorealistic/
            3D render instead of flat cartoon, OR a MAP shot with inaccurate/missing highlighted
            region, OR a CHART shot that doesn't represent the described data or is illegible
            (a MAP/CHART/PHOTO shot correctly having no cartoon mascot is NEVER a style failure —
            only fail PHOTO/MAP/CHART style if it fails ITS OWN type's guide above); content
            completely wrong/unrecognisable; obvious generation artifacts (extra limbs, distorted
            shapes, blurry key areas); confirmed typo in a key number or proper noun; image is
            off-topic (completely different subject); watermark present.
            Do NOT fail a CARTOON shot for: expressive cartoon faces (correct style), vibrant
            colors (correct), detailed mascot character (correct).
            Do NOT fail a PHOTO shot for being photorealistic — that IS the required style.
            Do NOT fail a MAP or CHART shot for looking like a plain map/chart instead of a
            cartoon illustration — that IS the required style.
            Do NOT fail any shot type for missing overlay text (PIL handles that separately).

Respond with ONLY this JSON (no markdown, no explanation):
{{
  "verdict": "PASS" | "WARN" | "FAIL",
  "style_ok": true | false,
  "content_match": true | false,
  "overlay_ok": true | false,
  "ratio_ok": true | false,
  "no_artifacts": true | false,
  "no_typos": true | false,
  "on_topic": true | false,
  "no_watermark": true | false,
  "typos_found": ["list of wrong text → correct text, or empty list"],
  "notes": "one concise sentence describing all issues found, or 'Looks good.' if none"
}}
"""


# ═══════════════════════════════════════════════════════════════════════════════
# PARSE PROMPTS FILE
# ═══════════════════════════════════════════════════════════════════════════════

def parse_prompts(md_path: str) -> list[dict]:
    """
    Parse image_prompts_one_line_per_prompt.md into a list of shot dicts.
    Each dict has: shot, filename, narration, prompt, overlay, cue, type

    `type` is looked up via route_images.parse_shots(), which applies the same
    TYPE/MAP_ARGS/CHART_ARGS validation and CARTOON-downgrade fallback used at
    generation time — so the review judges each shot against the style it was
    ACTUALLY routed/generated as, not just a raw (possibly stale) TYPE field.

    `chart_args`/`map_args` are captured the same way — CHART/MAP shots are
    rendered by generate_chart.py/generate_india_map.py from ONLY these
    structured args, never from the free-text PROMPT/INTENDED VISUAL (which
    still describes a narrative concept — often including the channel mascot —
    that these shot types never actually render). Passing the real args lets
    the reviewer judge CHART/MAP content against what was actually asked to be
    drawn, instead of a mascot-inclusive description that will never match.
    """
    shot_meta = {
        s["shot_num"]: s for s in route_images.parse_shots(Path(md_path))
    }
    type_by_shot_num = {num: s["type"] for num, s in shot_meta.items()}
    args_by_shot_num = {
        num: (s.get("chart_args") or s.get("map_args") or "")
        for num, s in shot_meta.items()
    }

    shots = []
    with open(md_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line.startswith("**SHOT"):
                continue

            # SHOT number
            shot_m = re.search(r"\*\*SHOT (\d+)\*\*", line)
            if not shot_m:
                continue
            shot = f"SHOT {shot_m.group(1).zfill(2)}"

            # Filename inside backticks
            fname_m = re.search(r"`([^`]+\.png)`", line)
            filename = fname_m.group(1) if fname_m else ""

            # NARRATION (quoted)
            narr_m = re.search(r'NARRATION:\s*"([^"]+)"', line)
            narration = narr_m.group(1) if narr_m else ""

            # PROMPT (between PROMPT: and OVERLAY:)
            prompt_m = re.search(r"PROMPT:\s*(.+?)\s*OVERLAY:", line)
            prompt = prompt_m.group(1) if prompt_m else ""

            # OVERLAY (between OVERLAY: and CUE:)
            overlay_m = re.search(r"OVERLAY:\s*(.+?)\s*CUE:", line)
            overlay = overlay_m.group(1) if overlay_m else ""

            # CUE (rest of line after CUE:)
            cue_m = re.search(r"CUE:\s*(.+)$", line)
            cue = cue_m.group(1) if cue_m else ""

            shot_num = int(shot_m.group(1))
            shots.append({
                "shot":       shot,
                "filename":   filename,
                "narration":  narration,
                "prompt":     prompt,
                "overlay":    overlay,
                "cue":        cue,
                "type":       type_by_shot_num.get(shot_num, "CARTOON"),
                "gen_args":   args_by_shot_num.get(shot_num, ""),
            })

    return shots


# ═══════════════════════════════════════════════════════════════════════════════
# IMAGE LOADING
# ═══════════════════════════════════════════════════════════════════════════════

def load_image_b64(image_path: str) -> tuple[str, str]:
    """Returns (base64_data, media_type)."""
    ext = Path(image_path).suffix.lower()
    media_map = {
        ".png":  "image/png",
        ".jpg":  "image/jpeg",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
    }
    media_type = media_map.get(ext, "image/png")
    with open(image_path, "rb") as f:
        return base64.standard_b64encode(f.read()).decode("utf-8"), media_type


# ═══════════════════════════════════════════════════════════════════════════════
# REVIEW ONE IMAGE
# ═══════════════════════════════════════════════════════════════════════════════

def review_image(client: anthropic.Anthropic, shot: dict,
                 image_path: str, model: str, title: str) -> dict:
    """Send one image to Claude and return the parsed review dict."""
    img_b64, media_type = load_image_b64(image_path)

    shot_type = shot.get("type", "CARTOON")
    style_guide = STYLE_GUIDES.get(shot_type, STYLE_GUIDES["CARTOON"])

    gen_args = shot.get("gen_args", "")
    gen_args_block = ""
    if shot_type in ("CHART", "MAP") and gen_args:
        label = "CHART_ARGS" if shot_type == "CHART" else "MAP_ARGS"
        gen_args_block = (
            f"GENERATION ARGS ({label}) — this is what actually generated the image, "
            f"NOT the free-text INTENDED VISUAL above: {gen_args}\n"
        )

    user_prompt = REVIEW_PROMPT.format(
        shot=shot["shot"],
        shot_type=shot_type,
        filename=shot["filename"],
        narration=shot["narration"],
        prompt=shot["prompt"],
        gen_args_block=gen_args_block,
        overlay=shot["overlay"],
        cue=shot["cue"],
        style_guide=style_guide,
        title=title,
    )

    # claude-sonnet-5 uses extended thinking by default, which eats into max_tokens
    # before any output text is generated — 768 was tuned for haiku (no thinking) and
    # left sonnet with too little headroom, in one confirmed case producing a response
    # with ONLY a thinking block and no text at all. Give sonnet calls more room.
    max_tokens = 4096 if model == MODELS["sonnet"] else 768

    response = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        messages=[{
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "source": {
                        "type": "base64",
                        "media_type": media_type,
                        "data": img_b64,
                    },
                },
                {"type": "text", "text": user_prompt},
            ],
        }],
    )

    # claude-sonnet-5 uses extended thinking by default, so content[0] may be a
    # ThinkingBlock rather than the text response — find the actual text block
    # instead of assuming it's first (haiku has no thinking block, so this is
    # a no-op there — content[0] is still the text block).
    text_block = next((b for b in response.content if b.type == "text"), None)
    if text_block is None:
        raise RuntimeError(f"No text block in response (blocks: {[b.type for b in response.content]})")
    raw = text_block.text.strip()

    # Strip markdown code fences if present
    raw = re.sub(r"^```(?:json)?\s*", "", raw)
    raw = re.sub(r"\s*```$", "", raw)

    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Fallback — extract verdict manually
        verdict = "WARN"
        if '"FAIL"' in raw or "'FAIL'" in raw:
            verdict = "FAIL"
        elif '"PASS"' in raw or "'PASS'" in raw:
            verdict = "PASS"
        return {
            "verdict":      verdict,
            "style_ok":     None,
            "content_match": None,
            "overlay_ok":   None,
            "ratio_ok":     None,
            "no_artifacts": None,
            "no_typos":     None,
            "on_topic":     None,
            "no_watermark": None,
            "typos_found":  [],
            "notes": f"[JSON parse error — raw: {raw[:120]}]",
        }


# ═══════════════════════════════════════════════════════════════════════════════
# REPORT WRITER
# ═══════════════════════════════════════════════════════════════════════════════

VERDICT_ICON = {"PASS": "✓", "WARN": "⚠", "FAIL": "✗", "SKIP": "—", "ERROR": "💥"}


def bool_icon(v) -> str:
    if v is True:  return "✓"
    if v is False: return "✗"
    return "?"


def write_report(results: list[dict], output_path: str, model_key: str,
                 total_shots: int, fail_only: bool, recheck_count: int = 0):
    passes  = sum(1 for r in results if r["result"].get("verdict") == "PASS")
    warns   = sum(1 for r in results if r["result"].get("verdict") == "WARN")
    fails   = sum(1 for r in results if r["result"].get("verdict") == "FAIL")
    skips   = sum(1 for r in results if r["result"].get("verdict") == "SKIP")
    errors  = sum(1 for r in results if r["result"].get("verdict") == "ERROR")
    reviewed = len([r for r in results if r["result"].get("verdict") not in ("SKIP",)])

    model_line = f"**Model:** {MODELS.get(model_key, model_key)}"
    if recheck_count:
        model_line += f" (bulk pass) + {MODELS['sonnet']} recheck on {recheck_count} WARN/FAIL shot(s)"

    lines = [
        f"# Image Review Report — ep01",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        model_line,
        f"**Images reviewed:** {reviewed} / {total_shots}  "
        f"({'skipped ' + str(skips) + ' missing' if skips else 'all present'})",
        "",
        "## Summary",
        f"✓ PASS : {passes}",
        f"⚠ WARN : {warns}",
        f"✗ FAIL : {fails}",
        f"— SKIP : {skips}  ← image not found in images/",
        f"💥 ERROR: {errors}",
        "",
        "---",
        "",
        "## Results",
        "",
        "| Shot | File | Verdict | Style | Content | Overlay | Ratio | Artifacts | Typos | On-topic | Watermark | Notes |",
        "|------|------|---------|-------|---------|---------|-------|-----------|-------|----------|-----------|-------|",
    ]

    for r in results:
        res  = r["result"]
        v    = res.get("verdict", "?")
        icon = VERDICT_ICON.get(v, v)
        if fail_only and v == "PASS":
            continue
        row = (
            f"| {r['shot']} "
            f"| `{r['filename']}` "
            f"| {icon} {v} "
            f"| {bool_icon(res.get('style_ok'))} "
            f"| {bool_icon(res.get('content_match'))} "
            f"| {bool_icon(res.get('overlay_ok'))} "
            f"| {bool_icon(res.get('ratio_ok'))} "
            f"| {bool_icon(res.get('no_artifacts'))} "
            f"| {bool_icon(res.get('no_typos'))} "
            f"| {bool_icon(res.get('on_topic'))} "
            f"| {bool_icon(res.get('no_watermark'))} "
            f"| {res.get('notes', '')} |"
        )
        lines.append(row)

    # Issues section
    issues = [r for r in results if r["result"].get("verdict") in ("WARN", "FAIL", "ERROR")]
    if issues:
        lines += ["", "---", "", "## Issues requiring attention", ""]
        for r in issues:
            res  = r["result"]
            v    = res.get("verdict", "?")
            icon = VERDICT_ICON.get(v, v)
            lines.append(f"### {icon} {r['shot']} · `{r['filename']}` · {v}")
            lines.append(f"**Notes:** {res.get('notes', '—')}")
            checks = []
            for key, label in [
                ("style_ok",      "Style"),
                ("content_match", "Content"),
                ("overlay_ok",    "Overlay"),
                ("ratio_ok",      "Ratio"),
                ("no_artifacts",  "No artifacts"),
                ("no_typos",      "No typos"),
                ("on_topic",      "On-topic"),
                ("no_watermark",  "No watermark"),
            ]:
                checks.append(f"{bool_icon(res.get(key))} {label}")
            lines.append("  " + "  ·  ".join(checks))
            typos = res.get("typos_found", [])
            if typos:
                lines.append(f"**Typos found:** {' | '.join(typos)}")
            lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="AI image review for The Interested Indian pipeline"
    )
    parser.add_argument("--project", required=True,
                        help="Project folder (e.g. ep01), relative or absolute")
    parser.add_argument("--shot", type=int, default=None,
                        help="Review a single shot number (e.g. --shot 7)")
    parser.add_argument("--fail-only", action="store_true",
                        help="Only show WARN/FAIL entries in the report table")
    parser.add_argument("--model", choices=["haiku", "sonnet"], default=DEFAULT_MODEL,
                        help=f"Claude model to use for the bulk pass (default: {DEFAULT_MODEL})")
    parser.add_argument("--no-recheck", action="store_true",
                        help="Skip the automatic Sonnet recheck of WARN/FAIL shots (haiku-only run)")
    args = parser.parse_args()

    # ── resolve paths ──────────────────────────────────────────────────────────
    script_dir  = Path(__file__).parent
    project_dir = (
        Path(args.project) if Path(args.project).is_absolute()
        else (script_dir / args.project).resolve()
    )
    if not project_dir.is_dir():
        print(f"❌ Project folder not found: {project_dir}")
        sys.exit(1)

    prompts_path = project_dir / PROMPTS_FILE
    if not prompts_path.exists():
        print(f"❌ Prompts file not found: {prompts_path}")
        print(f"   Expected: {PROMPTS_FILE} inside the project folder")
        sys.exit(1)

    images_dir   = project_dir / "images"
    report_path  = project_dir / "review_report.md"
    model_name   = MODELS[args.model]

    # Read the actual episode title from manifest.json so on-topic/typo checks
    # judge against THIS project, not a fixed placeholder topic. Previously
    # hardcoded to "Article 356" (this reviewer's original test episode),
    # which silently produced false on-topic FAILs for every other project.
    title = project_dir.name.replace("_", " ").title()
    manifest_path = project_dir / "manifest.json"
    if manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            title = manifest.get("title") or title
        except (json.JSONDecodeError, OSError):
            pass

    # ── load prompts ───────────────────────────────────────────────────────────
    shots = parse_prompts(str(prompts_path))
    if not shots:
        print("❌ No shots parsed from prompts file — check the format.")
        sys.exit(1)

    # Filter to single shot if requested
    if args.shot is not None:
        target = f"SHOT {str(args.shot).zfill(2)}"
        shots = [s for s in shots if s["shot"] == target]
        if not shots:
            print(f"❌ {target} not found in prompts file.")
            sys.exit(1)

    # ── init Anthropic client ──────────────────────────────────────────────────
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        # Try .env in script folder
        env_file = script_dir / ".env"
        if env_file.exists():
            for line in env_file.read_text().splitlines():
                if line.startswith("ANTHROPIC_API_KEY="):
                    api_key = line.split("=", 1)[1].strip().strip('"').strip("'")
                    break
    if not api_key:
        print("❌ ANTHROPIC_API_KEY not set.")
        print("   Set it as an environment variable or add it to a .env file:")
        print("   ANTHROPIC_API_KEY=sk-ant-...")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)

    # ── review loop ────────────────────────────────────────────────────────────
    print(f"\n{'═' * 55}")
    print(f"Image Review — {project_dir.name}")
    print(f"Title     : {title}")
    print(f"Model     : {model_name}")
    print(f"Shots     : {len(shots)}")
    print(f"Images dir: {images_dir}")
    print(f"{'═' * 55}\n")

    results = []

    for i, shot in enumerate(shots, 1):
        filename = shot["filename"]

        # Find image file (try exact name, then case-insensitive)
        image_path = images_dir / filename
        if not image_path.exists():
            # Try other extensions
            stem = Path(filename).stem
            found = None
            for ext in [".png", ".jpg", ".jpeg", ".webp"]:
                candidate = images_dir / f"{stem}{ext}"
                if candidate.exists():
                    found = candidate
                    break
            image_path = found

        if not image_path:
            print(f"[{i:02d}/{len(shots)}] {shot['shot']} · {filename}  — SKIP (not found)")
            results.append({
                "shot":     shot["shot"],
                "filename": filename,
                "result": {
                    "verdict":       "SKIP",
                    "style_ok":      None,
                    "content_match": None,
                    "overlay_ok":    None,
                    "ratio_ok":      None,
                    "no_artifacts":  None,
                    "no_typos":      None,
                    "on_topic":      None,
                    "no_watermark":  None,
                    "typos_found":   [],
                    "notes":         "Image file not found in images/",
                },
            })
            continue

        print(f"[{i:02d}/{len(shots)}] {shot['shot']} · {filename}", end="  ", flush=True)

        try:
            review = review_image(client, shot, str(image_path), model_name, title)
            verdict = review.get("verdict", "?")
            icon    = VERDICT_ICON.get(verdict, verdict)
            print(f"{icon} {verdict}  — {review.get('notes', '')}")
            results.append({
                "shot":     shot["shot"],
                "filename": filename,
                "result":   review,
            })
        except Exception as e:
            print(f"💥 ERROR — {e}")
            results.append({
                "shot":     shot["shot"],
                "filename": filename,
                "result": {
                    "verdict":       "ERROR",
                    "style_ok":      None,
                    "content_match": None,
                    "overlay_ok":    None,
                    "ratio_ok":      None,
                    "no_artifacts":  None,
                    "no_typos":      None,
                    "on_topic":      None,
                    "no_watermark":  None,
                    "typos_found":   [],
                    "notes":         str(e)[:120],
                },
            })

        if i < len(shots):
            time.sleep(DELAY_BETWEEN_CALLS)

    # ── sonnet recheck of WARN/FAIL shots ──────────────────────────────────────
    # Haiku is the cheap default but occasionally hallucinates a verdict (confirmed
    # on real shots — e.g. flagging a correct flat-cartoon image as "photorealistic").
    # Rather than paying Sonnet's higher per-image cost on the whole batch, only the
    # shots that already came back WARN/FAIL get a second opinion from Sonnet, which
    # becomes the final verdict for that shot. Skipped entirely if the bulk pass was
    # already Sonnet (redundant) or --no-recheck was passed.
    recheck_targets = [
        r for r in results if r["result"].get("verdict") in ("WARN", "FAIL")
    ]
    if args.model != "sonnet" and not args.no_recheck and recheck_targets:
        print(f"\n{'─' * 55}")
        print(f"Sonnet recheck — {len(recheck_targets)} WARN/FAIL shot(s)")
        print(f"{'─' * 55}\n")

        shots_by_key = {(s["shot"], s["filename"]): s for s in shots}
        sonnet_model_name = MODELS["sonnet"]

        for i, r in enumerate(recheck_targets, 1):
            shot = shots_by_key.get((r["shot"], r["filename"]))
            if shot is None:
                continue
            image_path = images_dir / r["filename"]
            if not image_path.exists():
                continue

            original_verdict = r["result"].get("verdict")
            print(f"[{i:02d}/{len(recheck_targets)}] {r['shot']} · {r['filename']}"
                  f"  (was {original_verdict})", end="  ", flush=True)
            try:
                recheck = review_image(client, shot, str(image_path), sonnet_model_name, title)
                verdict = recheck.get("verdict", "?")
                icon = VERDICT_ICON.get(verdict, verdict)
                print(f"→ {icon} {verdict}  — {recheck.get('notes', '')}")
                recheck["notes"] = (
                    f"[Sonnet recheck, Haiku said {original_verdict}] "
                    f"{recheck.get('notes', '')}"
                ).strip()
                r["result"] = recheck
            except Exception as e:
                print(f"💥 recheck ERROR — {e} (keeping original {original_verdict})")

            if i < len(recheck_targets):
                time.sleep(DELAY_BETWEEN_CALLS)

    # ── write report ───────────────────────────────────────────────────────────
    did_recheck = args.model != "sonnet" and not args.no_recheck and bool(recheck_targets)
    write_report(results, str(report_path), args.model,
                 total_shots=len(shots), fail_only=args.fail_only,
                 recheck_count=len(recheck_targets) if did_recheck else 0)

    passes = sum(1 for r in results if r["result"].get("verdict") == "PASS")
    warns  = sum(1 for r in results if r["result"].get("verdict") == "WARN")
    fails  = sum(1 for r in results if r["result"].get("verdict") == "FAIL")
    skips  = sum(1 for r in results if r["result"].get("verdict") == "SKIP")

    print(f"\n{'═' * 55}")
    print(f"Review complete")
    print(f"  ✓ PASS : {passes}")
    print(f"  ⚠ WARN : {warns}")
    print(f"  ✗ FAIL : {fails}")
    print(f"  — SKIP : {skips}")
    print(f"\nReport: {report_path}")
    print(f"{'═' * 55}\n")

    if warns + fails > 0:
        sys.exit(1)   # non-zero exit so CI pipelines can catch issues


if __name__ == "__main__":
    main()
